<script>
  import "@fontsource-variable/alegreya";
  import "@fontsource-variable/anybody";
  import "@fontsource-variable/ballet";
  import "@fontsource-variable/baloo-2";
  import "@fontsource-variable/bitter";
  import "@fontsource-variable/briem-hand";
  import "@fontsource-variable/caveat";
  import "@fontsource-variable/cinzel";
  import "@fontsource-variable/comfortaa";
  import "@fontsource-variable/crimson-pro";
  import "@fontsource-variable/dancing-script";
  import "@fontsource-variable/dm-sans";
  import "@fontsource-variable/eb-garamond";
  import "@fontsource-variable/edu-nsw-act-foundation";
  import "@fontsource-variable/edu-qld-beginner";
  import "@fontsource-variable/edu-sa-beginner";
  import "@fontsource-variable/edu-tas-beginner";
  import "@fontsource-variable/edu-vic-wa-nt-beginner";
  import "@fontsource-variable/grandstander";
  import "@fontsource-variable/inter";
  import "@fontsource-variable/lora";
  import "@fontsource-variable/manrope";
  import "@fontsource-variable/merienda";
  import "@fontsource-variable/montserrat";
  import "@fontsource-variable/mulish";
  import "@fontsource-variable/museomoderno";
  import "@fontsource-variable/noto-sans";
  import "@fontsource-variable/noto-serif";
  import "@fontsource-variable/nunito";
  import "@fontsource-variable/open-sans";
  import "@fontsource-variable/oxanium";
  import "@fontsource-variable/piazzolla";
  import "@fontsource-variable/pixelify-sans";
  import "@fontsource-variable/playfair-display";
  import "@fontsource-variable/playpen-sans";
  import "@fontsource-variable/public-sans";
  import "@fontsource-variable/raleway";
  import "@fontsource-variable/roboto-condensed";
  import "@fontsource-variable/roboto-slab";
  import "@fontsource-variable/shantell-sans";
  import "@fontsource-variable/tektur";
  import "@fontsource-variable/tourney";
  import "@fontsource-variable/rubik";
  import "@fontsource-variable/fraunces";
  import '@fontsource-variable/yrsa';
	import '@fontsource-variable/aleo';
	import '@fontsource-variable/nunito-sans';
	import '@fontsource-variable/roboto-flex';

  import "../app.css";
</script>

<slot />